disabled_rules:
  - todo
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - first_where
line_length:
  warning: 130
  error: 200
  ignores_comments: true
type_body_length:
  warning: 400
file_length:
  warning: 500
  error: 800
identifier_name:
  min_length: 1        # allow x, y, a, b in math
  excluded: [id, db, ai, ui, x, y, a, b, i, j, k, n, r, g, we]
excluded:
  - .build
  - DerivedData
  - Tests
